<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Tipe Data dan Variabel”**

**Disusun Oleh :**

**Rio Ardhan Maulana**

**2611532026**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Rifky Yuliandra**

<br>

 <img src="images/Logo_Unand.jpg" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur kehadirat Tuhan Yang Maha Esa atas segala rahmat dan karunia-Nya sehingga penulis dapat menyelesaikan laporan praktikum Pemrograman Python Pekan 2 yang berjudul “Tipe Data dan Variabel” dengan baik.

Laporan ini disusun sebagai bentuk dokumentasi dari kegiatan praktikum yang telah dilaksanakan. Pada praktikum Pekan 2, penulis mempelajari beberapa konsep dasar dalam pemrograman Python, yaitu boolean, input, konstanta, numerik, dan string. Materi tersebut merupakan dasar yang penting dalam pembuatan suatu program karena berkaitan dengan cara menyimpan, menerima, dan mengolah berbagai jenis data.

Melalui kegiatan praktikum ini, penulis dapat memahami penggunaan berbagai tipe data serta penerapannya dalam program Python sederhana. Selain memahami teori, praktikum juga memberikan kesempatan kepada penulis untuk melakukan percobaan secara langsung sehingga dapat mengetahui cara kerja setiap konsep yang dipelajari.

Penulis menyadari bahwa laporan ini masih jauh dari sempurna dan masih terdapat kekurangan dalam penyusunan maupun pembahasannya. Oleh karena itu, penulis mengharapkan kritik dan saran yang membangun untuk penyempurnaan laporan di masa yang akan datang.

Akhir kata, penulis mengucapkan terima kasih kepada dosen pembimbing dan semua pihak yang telah membantu dalam pelaksanaan praktikum serta penyusunan laporan ini. Semoga laporan ini dapat memberikan manfaat dan menambah pengetahuan mengenai dasar-dasar pemrograman Python.

Padang, 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Pemrograman merupakan salah satu bagian penting dalam bidang teknologi informasi yang digunakan untuk memberikan instruksi kepada komputer agar dapat melakukan suatu pekerjaan sesuai dengan kebutuhan pengguna. Dalam mempelajari pemrograman, diperlukan pemahaman terhadap konsep-konsep dasar seperti data, variabel, input, dan proses pengolahan data.

Python merupakan salah satu bahasa pemrograman yang banyak digunakan karena memiliki sintaks yang sederhana dan mudah dipahami. Python dapat digunakan untuk berbagai keperluan, mulai dari pembuatan aplikasi sederhana, pengolahan data, hingga pengembangan perangkat lunak. Oleh karena itu, pemahaman terhadap dasar-dasar bahasa Python sangat diperlukan bagi pemula sebelum mempelajari materi yang lebih kompleks.

Pada praktikum Pekan 2, dipelajari beberapa konsep dasar yang berkaitan dengan data dalam Python, yaitu boolean, input, konstanta, numerik, dan string. Boolean digunakan untuk merepresentasikan nilai benar atau salah (True atau False). Input digunakan untuk menerima data yang diberikan oleh pengguna ketika program dijalankan. Konstanta merupakan nilai yang pada konsepnya ditetapkan dan tidak seharusnya berubah selama program berjalan. Sementara itu, data numerik digunakan untuk menyimpan nilai berupa angka, sedangkan string digunakan untuk menyimpan data berupa teks atau karakter.

Pemahaman mengenai berbagai jenis data tersebut sangat penting karena hampir setiap program membutuhkan proses menerima, menyimpan, dan mengolah data. Dengan memahami karakteristik masing-masing jenis data, programmer dapat menentukan cara yang tepat dalam menggunakan data di dalam sebuah program.

Oleh karena itu, praktikum Pekan 2 dilaksanakan untuk memberikan pemahaman dan pengalaman secara langsung dalam menggunakan boolean, input, konstanta, numerik, dan string pada Python. Dengan adanya praktikum ini, diharapkan mahasiswa mampu menerapkan konsep-konsep tersebut dalam pembuatan program sederhana serta memiliki dasar yang kuat untuk mempelajari materi pemrograman Python pada pertemuan berikutnya.

## 1.2 Tujuan
1. Memahami pengertian variabel dalam Python.
2. Mengetahui berbagai macam tipe data yang terdapat pada Python.
3. Mengetahui cara membuat dan menggunakan variabel.
4. Memahami penggunaan tipe data input, numerik, string, konstanta, dan boolean.
5. Mampu menampilkan nilai variabel menggunakan fungsi print().
6. Mampu melakukan pengecekan tipe data menggunakan fungsi type()

## 1.3 Manfaat
1. Memahami tipe data dasar Python, khususnya boolean, numerik, dan string.
2. Mengetahui penggunaan input untuk menerima data dari pengguna saat program dijalankan.
3. Memahami konsep konstanta dan penerapannya dalam pembuatan program.
4. Meningkatkan kemampuan dalam membuat program sederhana menggunakan Python.
5. Melatih ketelitian dalam menulis kode program, terutama dalam menentukan jenis dan penggunaan data.
6. Memahami cara mengolah berbagai jenis data sehingga dapat digunakan sesuai kebutuhan program.
7. Menjadi dasar untuk mempelajari materi Python selanjutnya, seperti operator, percabangan, perulangan, fungsi, dan pengolahan data.

---
# BAB II
# PEMBAHASAN

## 2.1 Landasan Teori

**1. Pengenalan Bahasa Pemrograman Python**

Python merupakan salah satu bahasa pemrograman tingkat tinggi yang menggunakan konsep interpreted, object-oriented, dan dynamically typed. Python pertama kali dikembangkan oleh Guido van Rossum pada tahun 1991. Bahasa ini dirancang dengan sintaks yang sederhana dan mudah dibaca, sehingga cukup banyak digunakan untuk pembelajaran maupun pengembangan program. Python dapat diterapkan dalam berbagai bidang, seperti pembuatan perangkat lunak, otomatisasi, analisis data, dan kecerdasan buatan.

​**2. Konsep Variabel dalam Python**

Variabel digunakan untuk menyimpan sebuah nilai yang nantinya dapat digunakan kembali dalam program. Pada Python, variabel dapat dibuat secara langsung dengan memberikan nilai menggunakan tanda = tanpa harus menentukan tipe datanya terlebih dahulu. Dalam penulisannya, nama variabel memiliki beberapa aturan, seperti membedakan huruf besar dan kecil (case-sensitive), tidak boleh diawali angka, serta tidak dapat menggunakan kata kunci yang sudah digunakan oleh Python.

**​3. Tipe Data Dasar**

Tipe data menunjukkan jenis nilai yang disimpan dalam sebuah variabel. Python memiliki beberapa tipe data dasar yang sering digunakan, yaitu:

-Integer (int): digunakan untuk menyimpan bilangan bulat, seperti -5, 0, dan 100.

-Float (float): digunakan untuk menyimpan bilangan yang memiliki nilai desimal, seperti 3.14 dan -0.01.

-String (str): digunakan untuk menyimpan teks atau kumpulan karakter yang ditulis menggunakan tanda petik, seperti "Praktikum Python".

-Boolean (bool): digunakan untuk menyimpan nilai logika yang terdiri dari True dan False.

**​4. Dynamic Typing dan Type Casting**

Python menggunakan sistem dynamic typing, yaitu tipe data variabel dapat ditentukan secara otomatis berdasarkan nilai yang diberikan ketika program dijalankan. Python juga menyediakan type casting yang digunakan untuk mengubah suatu nilai dari satu tipe data ke tipe lainnya. Contohnya adalah penggunaan int(), float(), dan str(). Pemahaman mengenai type casting diperlukan agar data dapat digunakan sesuai dengan operasi yang dilakukan dan mengurangi kemungkinan terjadinya type error.

## 2.2 Kode Program

### 2.2.1 Program "Boolean_2611532026"

In [ ]:
# Buat file dengan nama Booleean_NIM.py
# Nama variabel ditambah 4 digit nim terakhir contoh: nilai_1234
# Deklarasi variabel dengan type data Boolean
is_lulus_2026 = True
is_cumlaude_2026 = True

# Menggunakan Boolean
nilai_2026 = 85
batal_lulus_2026 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_2026 = nilai_2026 >= batal_lulus_2026 # Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai_2026:", nilai_2026)
print("Apakah Lulus?:", status_kelulusan_2026)
if is_lulus_2026 and is_cumlaude_2026:
    print("Selamat, Anda lulus dengan predikat cumlaude!")

=== Check Kelulusan ===
Nilai: 85
Apakah lulus: True


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel Boolean is_lulus_2026 dengan nilai True dan is_cumlaide_2026 dengan nilai True.
2. Bagian 3 sampai 4 berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel.
3. Bagian 6 sampai 8 berfungsi untuk menampilkan judul, nilai mahasiswa, dan hasil status kelulusan ke layar.

### 2.2.2 Program "Input_2611532026"

In [ ]:
# Buat file dengan nama Input_NIM.py
# Buat program untuk menghitung luas persegi panjang
# Nama variabel ditambah 4 digit nim terakhir conto: panjang_1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# memasukkan nilai pnjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_2026 = input('Masukkan nilai panjang: ')
lebar_2026 = input('Masukkan nilai lebar: ')
luas_2026 = int(panjang_2026) * int(lebar_2026)
print("Luas =", luas_2026)

Masukkan panjang: 10
Masukkan lebar: 5
Luas persegi panjang adalah: 50


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk meminta pengguna memasukkan nilai panjang dan lebar persegi panjang menggunakan fungsi input().
2. Bagian 3 berfungsi untuk mengubah nilai panjang dan lebar menjadi tipe data integer, kemudian menghitung luas persegi panjang.
3. Bagian 4 berfungsi untuk menampilkan hasil perhitungan luas persegi panjang ke layar.

### 2.2.3 Program "Konstanta_2611532026"

In [ ]:
# Buat file dengan nama Konstanta_NIM.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variabel ditambah 4 digit nim terakhir contoh: jari_1234
from typing import Final, final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_2026 = float(input('Masukkan nilai jari-jari: '))
luas_2026 = PI * jari_2026 * jari_2026
print("Luas lingkaran dengan jari-jari %.2f adalh %.2f" % (jari_2026, luas_2026))

 3.140000
Masukkan jari-jari lingkaran: 10
Luas lingkaran dengan jari-jari 10.00 adalah 314.00


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk mengimpor Final dan menentukan nilai konstanta PI sebesar 3.14.
2. Bagian 3 sampai 4 berfungsi untuk menampilkan nilai PI dan meminta pengguna memasukkan nilai jari-jari lingkaran.
3. Bagian 5 berfungsi untuk menghitung luas lingkaran menggunakan nilai PI dan jari-jari yang telah dimasukkan.
4. Bagian 6 berfungsi untuk menampilkan hasil perhitungan luas lingkaran dengan format dua angka di belakang koma.

### 2.2.4 Program "Numerik_2611532026"

In [ ]:
# Buat file dengan nama Numerik_2611532026.py
# nama variabel ditambah 4 digit terakhir NIM contoh: a_1234
#create variabel a variabel with numerik type value.
a_2026=100
print("The type of variabel having value", a_2026, " is ", type(a_2026))

#create a variabel with float value.
b_2026=10.2345
print("The type of variabel having value", b_2026, " is ", type (b_2026))

#create a variabel with complex value.
c_2026=100+3j
print("The type of variabel having value", c_2026, " is", type (c_2026))

The type of variable having value 100 is <class 'int'>
The type of variable having value 10.2345 is <class 'float'>
The type of variable having value (100+3j) is <class 'complex'>


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel a_2026 dengan nilai 100 dan menampilkan nilai serta tipe datanya menggunakan fungsi type().
2. Bagian 3 sampai 4 berfungsi untuk membuat variabel b_2026 dengan nilai 10.2345 dan menampilkan nilai serta tipe datanya.
3. Bagian 5 sampai 6 berfungsi untuk membuat variabel c_2026 dengan nilai kompleks 100+3j dan menampilkan nilai serta tipe datanya.

### 2.2.5 Program "String_2611532026"

In [ ]:
# Buat file dengan nama String_NIM.py
#nama variabel ditambah 4 digit nim terakhir contoh: a_1234
#ganti programnya dan data masing2
nama_2026 = "Rio Ardhan Maulana"
jenis_kelamin_2026 = "Laki-laki"
alamat_2026 = """
   Kampus Unand
   Kec.pauh
   Kota Padang
"""
agama_2026 = "islam"
print("Nama saya adalah: ", nama_2026)
print("Jenis kelamin saya adalah: ", jenis_kelamin_2026)
print("Alamat saya adalah: ", alamat_2026)
print("Agama saya adalah: ", agama_2026)

In [ ]:
nama saya adalah: Rio Ardhan Maulana
jenis kelamin saya adalah: Laki-laki
alamat saya adalah:
    Kampus Unand
    Kec.pauh
    Kota Padang
agama saya adalah: islam

**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel nama_2026 dan jenis_kelamin_2026 yang menyimpan data nama dan jenis kelamin.
2. Bagian 3 sampai 7 berfungsi untuk membuat variabel alamat_2026 yang menyimpan data alamat dalam bentuk string yang terdiri dari beberapa baris.
3. Bagian 8 berfungsi untuk membuat variabel agama_2026 yang menyimpan data agama.
4. Bagian 9 sampai 12 berfungsi untuk menampilkan nama, jenis kelamin, alamat, dan agama ke layar menggunakan fungsi print().

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan pada Pekan 2, dapat disimpulkan bahwa Boolean, Input, Konstanta, Numerik, dan String merupakan konsep dasar yang penting dalam pemrograman Python. Setiap jenis data memiliki fungsi dan karakteristik yang berbeda sehingga penggunaannya harus disesuaikan dengan kebutuhan program.

Tipe data Boolean digunakan untuk menyatakan nilai benar atau salah, Input digunakan untuk menerima data dari pengguna, Konstanta digunakan untuk menyimpan nilai yang bersifat tetap, Numerik digunakan untuk menyimpan dan melakukan operasi terhadap data berupa angka, sedangkan String digunakan untuk menyimpan data berupa teks atau kumpulan karakter.

Selain itu, melalui praktikum ini dapat dipahami bahwa data yang dimasukkan ke dalam program dapat diolah dan digunakan untuk menghasilkan informasi sesuai dengan tujuan program. Penggunaan variabel juga membantu dalam menyimpan data sehingga dapat dipanggil dan digunakan kembali selama program berjalan.

Dengan melakukan praktikum secara langsung, mahasiswa tidak hanya memahami teori, tetapi juga dapat mengetahui penerapan setiap konsep dalam kode Python. Pemahaman mengenai materi ini diharapkan dapat meningkatkan kemampuan dalam membuat program sederhana serta menjadi landasan untuk mempelajari materi pemrograman Python yang lebih lanjut, seperti operator, percabangan, perulangan, fungsi, dan struktur data.

---
## DAFTAR PUSTAKA

[1]  ​Lubanovic, B. (2019). Introducing Python: Modern Computing in Simple Packages (2nd ed.). O'Reilly Media. Link: https://www.oreilly.com/library/view/introducing-python-2nd/9781492051374/

[2] ​Matthes, E. (2019). Python Crash Course: A Hands-On, Project-Based Introduction to Programming (2nd ed.). No Starch Press. Link: https://nostarch.com/pythoncrashcourse2e

[3] ​Severance, C. R. (2016). Python for Everybody: Exploring Data in Python 3. CreateSpace Independent Publishing Platform. Link: https://www.py4e.com/book

[4] ​Swaroop, C. H. (2013). A Byte of Python. Link: https://python.swaroopch.com/